name: Publish Release

on:
  workflow_dispatch:

jobs:
  buildRelease:
    name: Build Release
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Setup Python enviroment
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gitignore_parser

      - name: Create pyromod and zip files
        run: |
          python .github/build_scripts/make_pyromod.py

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.PYROMOD_MOD_NAME }} v${{ env.PYROMOD_MOD_VERSION }}
          tag_name: v${{ env.PYROMOD_MOD_VERSION }}
          files: |
            ${{ env.PYROMOD_PYROMOD_FILE_PATH }}
            ${{ env.PYROMOD_ZIP_FILE_PATH }}
